type: aws-sqs
version: 0.2.0
core: 0.2.x

description: 'Provision AWS SQS components'
license: Apache-2.0
author: 'Serverless, Inc. <hello@serverless.com> (https://serverless.com)'
repository: 'github:serverless/components'

inputTypes:
  queueName:
    type: string
    required: true
    displayName: AWS SQS name
    description: The name of the SQS to create
    example: myQueue
  delaySeconds:
    type: string
    displayName: Delay Seconds
    description: The length of time, in seconds, for which the delivery of all messages in the queue is delayed
    example: '22'
  maximumMessageSize:
    type: string
    displayName: Maximum MessageSize
    description: The limit of how many bytes a message can contain before Amazon SQS rejects it. Valid values- An integer from 1,024 bytes (1 KiB) to 262,144 bytes (256 KiB)
    example: '1024'
  messageRetentionPeriod:
    type: string
    displayName: Message RetentionPeriod
    description: The length of time, in seconds, for which Amazon SQS retains a message. Valid values- An integer from 60 seconds (1 minute) to 1,209,600 seconds (14 days)
    example: '60'
  receiveMessageWaitTimeSeconds:
    type: string
    displayName: Receive Message Wait TimeSeconds
    description: The length of time, in seconds, for which a ReceiveMessage action waits for a message to arrive. Valid values- An integer from 0 to 20 (seconds)
    example: '2'
  visibilityTimeout:
    type: string
    displayName: Visibility Timeout
    description: The visibility timeout for the queue, in seconds. Valid values- An integer from 0 to 43,200 (12 hours). Default- 30.
    example: '20'
  fifoQueue:
    type: boolean
    displayName: Fifo Queue
    description: Designates a queue as FIFO. Valid values- true, false
    example: true
  contentBasedDeduplication:
    type: boolean
    displayName: Content Based Deduplication
    description: Enables content-based deduplication. Valid values- true, false
    example: false

outputTypes:
  queueUrl:
    type: string
    description: The name of the role
