type: github-webhook-example

components:
  webhookFunction:
    type: aws-lambda
    inputs:
      memory: 512
      timeout: 10
      handler: code/handler.githubFunction
  GithubWebhookAWS:
    type: github-webhook-aws
    inputs:
      function: ${webhookFunction}
      githubRepo: DavidTron5000/other-repo
      githubApiToken: xx
      webhookTriggers:
        - create
