type: s3-prototype

components:
  filesBucket:
    type: s3
    inputs:
      name: files
  filesTable:
    type: dynamodb
    inputs:
      name: files
  dowloaderLambda:
    type: lambda
    inputs:
      name: s3-downloader
      handler: downloader.handler
  uploaderLambda:
    type: lambda
    inputs:
      name: s3-uploader
      handler: uploader.handler
  uploaderSubscription:
    type: eventgateway-subscription
    inputs:
      event: http
      method: POST
      path: /upload
      id: s3-uploader
      arn: ${uploaderLambda:arn}
  downloaderSubscription:
    type: eventgateway-subscription
    inputs:
      event: fileUploaded
      id: s3-downloader # creates and deletes
      arn: ${downloaderLambda:arn} # creates and deletes
