type: s3-prototype

components:
  filesBucket:
    type: s3
    inputs:
      name: files
  filesTable:
    type: dynamodb
    inputs:
      name: files
  dowloaderLambda:
    type: lambda
    inputs:
      name: eslam-s3-downloader
      handler: downloader.handler
  uploaderLambda:
    type: lambda
    inputs:
      name: eslam-s3-uploader
      handler: uploader.handler
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: eslam/upload
      id: eslam-s3-uploader
      arn: ${uploaderLambda:arn}
  downloaderSubscription:
    type: eventgateway
    inputs:
      event: fileUploaded
      id: eslam-s3-downloader
      arn: ${downloaderLambda:arn}
