type: s3-prototype

components:
  filesBucket:
    type: s3
    inputs:
      name: serverless-components-eslam-files
  filesTable:
    type: dynamodb
    inputs:
      name: files
  downloaderLambda:
    type: lambda
    inputs:
      name: eahefnawy-downloader
      handler: downloader.handler
      env:
        EVENT_GATEWAY_TOKEN: ${EVENT_GATEWAY_TOKEN}
        FILES_TABLE: files
  uploaderLambda:
    type: lambda
    inputs:
      name: eahefnawy-uploader
      handler: uploader.handler
      env:
        EVENT_GATEWAY_TOKEN: ${EVENT_GATEWAY_TOKEN}
        BUCKET: serverless-components-eslam-files
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: eahefnawy-uploader
      id: eahefnawy-uploader
      arn: ${uploaderLambda:arn}
  downloaderSubscription:
    type: eventgateway
    inputs:
      event: fileUploaded
      id: eahefnawy-downloader
      arn: ${downloaderLambda:arn}
