type: aws-apigateway

inputTypes:
  name:
    type: string
    required: false
    default: apig-${self.instanceId}
  roleArn:
    type: string
    required: true
  routes:
    type: object
    required: true
