name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      credentials:
        accessKeyId: AKIAJKJ4Q2CPPX56MN6Q
        secretAccessKey: 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
      region: us-east-1

compute:
  type: AwsLambdaCompute
  inputs:
    provider: ${this.providers.aws}
    runtime: nodejs

functions:
  hello:
    compute: ${this.compute}
    handler: index.hello
    code: ./code
    memory: 1024
    timeout: 20
    ufs: true

components:
  cron:
    type: Cron
    inputs:
      function: ${this.functions.hello}
      rate: 4m
