name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      credentials:
        accessKeyId: xxx
        secretAccessKey: xxx
      region: us-east-1

compute:
  type: AwsLambdaCompute
  inputs:
    provider: ${this.providers.aws}
    runtime: nodejs

functions:
  hello:
    compute: ${this.compute}
    handler: index.hello
    code: ./code
    memory: 1024
