name: SimpleService
extends: Service

providers:
  aws:
    type: AwsProvider
    inputs:
      region: us-east-1

compute:
  type: AwsLambdaCompute
  inputs:
    provider: ${this.providers.aws}
    runtime: nodejs

functions:
  decemberdemo:
    compute: ${this.compute}
    handler: index.hello
    code: ./code
    memory: 1024
    timeout: 20

components:
  bucket:
    type: AwsS3Bucket
    inputs:
      provider: ${this.providers.aws}
  policy:
    type: AwsIamPolicy
    inputs:
      provider: ${this.providers.aws}
      document:
        Version: '2012-10-17'
        Statement:
          - Resource:
              - arn:aws:dynamodb:us-east-1:552750238299:table/idempotent-policy
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
