type: aws-iam-role

inputTypes:
  name:
    type: string
    required: false
    default: role-${self.instanceId}
  service:
    type: string
    required: true
  policy:
    type: object
    required: false
