language: node_js
sudo: false
node_js:
- 8
install:
- npm install
script:
- npm run lint
- npm test
env:
  SENTRY_DSN: https://17031d90871a4daebd4f261f2359b38f:9ce69587851c448b96893fb3794df20e@sentry.io/300239
  SEGMENT_WRITE_KEY: jvOP27GTlIJubkJpRcDAa4uSfwCD03NI
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: serverless/serverless-components
  api_key:
    secure: Q2l5ALxqdYj0CrS4WtdH0ovmjPUzEdNajLGdthTnBDRu0M8bFxLMvXLNblpj1Q2bJgNFWMBB81KE/Kv7+Jtnx/Hd3vfQdtc+fUwSGEO2zS2sg8BgCptx4warVqSsrEzW2qRpbqnhMkDBQ81ksW+jFSrcLWs1C7CYTz2fMkGyBk1eAt9guM7RQtvhbYiS5gInXVkKXudXAyLVJrfRMTRFB3fze61F9Clqk4SqDCx43Q448DjONvii89XwGKHLifv8WC/nACcCOZ9Fg1xpGdQZYtcNnTW4kSoLYpPzC0tmFmEagusjclkahMUywhKdGF/JFmX6zpZNhNPwH9i3FNuBFGT9ISYomUuL0AzbPGQa+q/tKl832cwKXA/SFS5jPhIQi38FXcdCcG0SOoLhlzP5HGprHower86F02I3Y3S8p2Zu9aPSY3X9UNsfN6OeFONk8vRvjqM7W9j0dpw9lSZLqpPh8P7I/m4I3VXSbTjzNpcYiScybE4frq7pOTfo9ty9jtETE8Cn9ovDrWwY6xiW+oluFq1863tNkkRJiLBMxeKqFAYkt07zzXN/jRMZc1eXzrRc1guvljm+Gkr9SCaa92/7OK8vBZHQywDWOrDIJKM++BYiGzynJ6ml7I9ET498HfEkc0OvwLwDSEiwxcg9EJr5sng5fUira8LrojBmSH8=
