name: github-webhook-receiver

inputs:
  lambdaArn: ${lambda:arn}
  lambdaRoleArn: ${lambda:roleArn}
  apiId: ${apigateway:id
  apiRoleArn: ${apigateway:roleArn}
  url: ${apigateway:url}
  tableName: ${dynamodb:name}
  webhookId: ${github:id}

components:
  dynamodb:
    type: dynamodb
    inputs:
      name: github-webhook-receiver
  lambda:
    type: lambda
    inputs:
      name: github-webhook-receiver
      memory: 128
      timeout: 10
      handler: code.handler
  apigateway:
    type: apigateway
    inputs:
      name: github-webhook-receiver
      method: POST
      path: /github/webhook/test
      lambda: ${lambda:arn}
  github:
    type: github
    inputs:
      token: ${GITHUB_TOKEN}
      owner: serverless
      repo: components-eslam
      url: ${apigateway:url}
      event: pull_request