name: AwsS3Website
extends: Component
main: ./dist/index.js
version: 1.0.0

provider: ${inputs.provider}
bucket: ${inputs.bucket}
assets: ${inputs.assets}
env: ${inputs.env}

inputTypes:
  provider:
    type: AwsProvider
    required: true
  bucket:
    type: string
    displayName: Bucket Name
    description: Your AWS S3 bucket name, which is also used as a domain.
    required: true
  assets:
    type: string
    displayName: Assets
    description: Path to static website assets
    required: true
  env:
    type: object
    displayName: Environment Variables
    description: Environment variables to be included in a script with the front-end assets
    required: false
