type: dynamodb

inputs:
  region: us-east-1
  deletionPolicy: Delete
  properties:
    tableName: 'my-table-name-wow'
    attributeDefinitions:
      - attributeName: number
        attributeType: N
    keySchema:
      - attributeName: number
        keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    globalSecondaryIndexes: null
    localSecondaryIndexes: null
    timeToLiveSpecification:
      attributeName: ttl
      enabled: true
    streamSpecification: null
    tags: null
    sSESpecification:
      sSEEnabled: false
