name: fullstack-app

# Frontend
frontend:
  component: "@serverless/website"
  inputs:
    code: ./frontend

# Functions
createUser:
  component: "@serverless/function"
  inputs:
    name: ${name}-create-user
    code: ./backend
    handler: index.createUser
getUsers:
  component: "@serverless/function"
  inputs:
    name: ${name}-get-users
    code: ./backend
    handler: index.getUsers
auth:
  component: "@serverless/function"
  inputs:
    name: ${name}-auth
    code: ./backend
    handler: index.auth
sendNotification:
  component: "@serverless/function"
  inputs:
    name: ${name}-send-notification
    code: ./backend
    handler: index.sendNotification

# REST API
restApi:
  component: "@serverless/api"
  inputs:
    name: ${name}-api
    description: Serverless REST API
    endpoints:
      - path: /users
        method: POST
        function: ${comp:createUser}
        authorizer: ${comp:auth}
      - path: /users
        method: GET
        function: ${comp:getUsers}
        authorizer: ${comp:auth}

# PubSub
subscriptions:
  component: "@serverless/subscriptions"
  inputs:
    - source: userCreated # topic name
      function: ${comp:sendNotification}
