type: tests-integration-function-mock

inputTypes:
  name:
    type: string
    required: true
  memorySize:
    type: number
    required: true
  timeout:
    type: number
    required: true
  role:
    type: string
    required: true
