name: my-realtime-app

app:
  component: "@serverless/realtime-app"
  inputs:
    frontend:
      assets: ./frontend
    backend:
      assets: ./backend
      env:
        dbMessages: ${comp:connectionsTable.name}

connectionsTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: ${name}-connections
