type: github-webhook-aws

inputTypes:
  function:
    type: string
    required: true
  githubApiToken:
    type: string
    required: true
  githubRepoOwner:
    type: string
    required: true
  githubRepoName:
    type: string
    required: true
  webhookTriggers:
    type: array
    required: true

components:
  GithubWebhook:
    type: github-webhook
    inputs:
      token: ${input.githubApiToken}
      owner: ${input.githubRepoOwner}
      repo: ${input.githubRepoName}
      url: ${webhookEndpoint.url}/webhook
      events: ${input.webhookTriggers}
  webhookEndpoint:
    type: rest-api
    inputs:
      gateway: aws-apigateway
      routes:
        /webhook: # routes begin with a slash
          post: # HTTP method names are used to attach handlers
            function: ${input.function}
            cors: true
