type: github-webhook-aws

inputTypes:
  function:
    type: string
    required: true
  githubApiToken:
    type: string
    required: true
  githubRepo:
    type: string
    required: true
  webhookTriggers:
    type: array
    required: true

components:
  GithubWebhook:
    type: github-webhook
    inputs:
      githubApiToken: ${input.githubApiToken}
      githubRepo: ${input.githubRepo}
      payloadUrl: ${webhookEndpoint.url}/webhook
      events: ${input.webhookTriggers}
  webhookEndpoint:
    type: rest-api
    inputs:
      gateway: aws-apigateway
      routes:
        /webhook: # routes begin with a slash
          post: # HTTP method names are used to attach handlers
            function: ${input.function}
            cors: true
