type: github-webhook-aws

inputTypes:
  handler:
    type: string
    required: true
  githubApiToken:
    type: string
    required: true
  githubRepo:
    type: string
    required: true
  webhookTriggers:
    type: array
    required: true

components:
  myGithubFunction:
    type: lambda
    inputs:
      name: myGithubFunction
      memory: 512
      timeout: 10
      handler: code/handler.githubFunction

inputs:
  handler: ${myGithubFunction}
  githubApiToken: xxx
  githubRepo: https://github.com/DavidTron5000/responsible/
  webhookTriggers:
    - create
