# static website component

type: rg-aws-staticweb
inputs:
  name: rgfamilysite
  contentPath: ./site
  contentIndex: index.html
  contentError: error.html
  hostingRegion: us-east-1
  hostingDomain: rgfamily.com
  aliasDomain: www.rgfamily.com

components:
  rootDomainBucket:
    type: s3
    inputs:
      name: ${rg-aws-staticweb.inputs.hostingDomain}
  rootDomainBucketPolicy:
    type: rg-s3policy
    inputs:
      bucketName: ${rootDomainBucket.outputs.name}
  siteContentUploader:
    type: rg-s3sync
    inputs:
      contentPath: ${rg-aws-staticweb.inputs.contentPath}
      bucketName: ${rootDomainBucket.outputs.name}
  wwwDomainBucket:
    type: s3
    inputs:
      name: ${rg-aws-staticweb.inputs.aliasDomain}
  rootDomainBucketConfig:
    type: rg-s3-website-config
    inputs:
      rootBucketName: ${rootDomainBucket.outputs.name}
      indexDocument: ${rg-aws-staticweb.inputs.contentIndex}
      errorDocument: ${rg-aws-staticweb.inputs.contentError}
      redirectBucketName: ${wwwDomainBucket.outputs.name}
      redirectToHostName: ${rg-aws-staticweb.inputs.hostingDomain}
  siteCloudFrontConfig:
    type: rg-cloudfront
    inputs:
      name: ${rg-aws-staticweb.inputs.name}
      defaultRootObject: ${rg-aws-staticweb.inputs.contentIndex}
      originId: ${rootDomainBucket.outputs.name}
      originDomain: rgfamily.com.s3.amazonaws.com
      aliasDomain: ${rg-aws-staticweb.inputs.aliasDomain}
      distributionEnabled: true
  siteRoute53Config:
    type: rg-route53
    inputs:
      name: ${rg-aws-staticweb.inputs.name}
      domainName: ${rg-aws-staticweb.inputs.aliasDomain}
      dnsName: ${siteCloudFrontConfig.outputs.distribution.domainName} # d111111abcdef8.cloudfront.net
