# TODO: move this to the "examples" directory
type: s3-downloader

inputs:
  name: abc

components:
  downloaderLambda:
    type: lambda
    inputs:
      name: ${input.name}
      handler: downloader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${EVENT_GATEWAY_API_KEY}
        FILES_TABLE: serverless-components-eslam-files
  downloaderSubscription:
    type: eventgateway
    inputs:
      event: fileUploaded
      space: eslam
      eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y
      lambdaArn: ${downloaderLambda.arn}
