type: cloudflare-workers
version: 1.0.0
description: 'Serverless components to deploy Cloudflare-Workers'

inputTypes:
        zone_id:
                type: string
                required: true
        script_path:
                type: string
                required: true
        account_id:
                type: string
                required: true
        script_name:
                type: string
                required: true
        routes:
                type: string
                required: true

outputTypes:
        successScript:
                type: boolean
                description: If worker script has been successfully deployed
        resultScript:
                type: any
                description: The resultant worker script uploaded
        errorsScript:
                type: any
                description: A list of error messages
        messagesScript:
                type: any
                description: Messages
        successRoute:
                type: boolean
                description: If worker script has been successfully deployed
        resultRoute:
                type: any
                description: The resultant worker script uploaded
        errorsRoute:
                type: any
                description: A list of error messages
        messagesRoute:
                type: any
                description: Messages

