type: s3-uploader

inputs:
  name: abc

components:
  uploaderLambda:
    type: lambda
    inputs:
      name: ${parent:name}
      handler: uploader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${EVENT_GATEWAY_API_KEY}
        BUCKET: serverless-components-eslam-files
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: ${parent:name}
      space: eslam
      eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y
      lambdaArn: ${uploaderLambda:arn}
