# TODO: move this to the "examples" directory
type: s3-uploader

inputTypes:
  name:
    type: string
    default: my-s3-uploader

components:
  uploaderLambda:
    type: lambda
    inputs:
      name: ${input.name}
      handler: uploader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${EVENT_GATEWAY_API_KEY}
        BUCKET: serverless-components-eslam-files
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: ${input.name}
      space: eslam
      eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y
      lambdaArn: ${uploaderLambda.arn}
