type: eventgateway

inputTypes:
  event:
    type: string
    required: true
  path:
    type: string
    required: true
  method:
    type: string
    required: false
  cors:
    type: boolean
    required: false
  space:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: false
  lambdaArn:
    type: string
    required: true
