type: eventgateway

inputs:
  event: http
  path: some-path
  method: GET
  cors: true
  space: some-space
  eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y
  lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:some-lambda-function
