type: netlify-site-example

components:
  myNetlifySite:
    type: netlify-site
    inputs:
      netlifyApiToken: xxx
      githubApiToken: yyy
      siteName: my-awesome-site-lol-lol.netlify.com
      siteDomain: testing-lol-lol-lol.com
      siteRepo: https://github.com/DavidTron5000/responsible
      siteBuildDirectory: demo
      siteEnvVars:
        foo: bar
        baz: faas
      siteRepoBranch: other-branch
      siteRepoAllowedBranches:
          - other-branch
