type: rest-api

inputTypes:
  gateway:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: false
  space:
    type: string
    required: false
  name:
    type: string
    required: true
  routes:
    type: object
    required: true
