type: rest-api

inputs:
  gateway: apigateway
  eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y # optional
  space: some-space # optional
  name: some-rest-api
  routes:
    /products: # path entries must start with a slash
      post: # method entries do not start with a slash
        lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:create-product-lambda
      /{id}: # path parameters are in curly braces
        get:
          lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:get-product-lambda
          cors: true
        put:
          lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:update-product-lambda
        delete:
          lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:delete-product-lambda
