type: rest-api

inputs:
  gateway: apigateway
  eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y # optional
  space: some-space # optional
  name: some-rest-api
  routes:
    /products: # routes begin with a slash
      post: # HTTP method names are used to attach handlers
        function:
          arn: arn:aws:lambda:us-east-1:XXXXX:function:create-product

      # sub-routes can be declared hierarchically
      /{id}: # path parameters use curly braces
        get:
          function:
            arn: arn:aws:lambda:us-east-1:XXXXX:function:get-product
          cors: true # CORS can be allowed with this flag

    # multi-segment routes can be declared all at once
    /catalog/{...categories}: # catch-all path parameters use ellipses
        get:
          function:
            arn: arn:aws:lambda:us-east-1:XXXXX:function:list-products
          cors: true
