type: cloudflare-worker-application

components:
        myWorker:
                type: cloudflare-workers
                inputs:
                        zone_id: '66de06a610e659edd89a6de59df291d2'
                        script_path: '/Users/nirvikghosh/service_workers_playground/Serverless/crap.js'
                        account_id: '5ea9ff246c8fd83268943de928d5109a'
                        script_name: 'stupid'
                        routes: 'nirvik.me/boss/*'
