name: TwilioProvider
extends: Provider
version: 1.0.0
main: ./index.js

accountSid: ${inputs.accountSid}
authToken: ${inputs.authToken}

inputTypes:
  accountSid:
    type: string
    require: true
  authToken:
    type: string
    require: true
