type: github

inputTypes:
  token:
    type: string
    required: true
  owner:
    type: string
    required: true
  repo:
    type: string
    required: true
  url:
    type: string
    required: true
  event:
    type: string
    required: true
