type: github-webhook-receiver

inputs:
  url: ${myEndpoint:url}

components:
  myTable:
    type: dynamodb
    inputs:
      name: github-webhook-receiver
  myFunction:
    type: lambda
    inputs:
      name: github-webhook-receiver-function
      memory: 512
      timeout: 10
      handler: code.handler
  myEndpoint:
    type: apigateway
    inputs:
      name: github-webhook-receiver-api
      roleArn: arn:aws:iam::XXXXX:role/some-api-gateway-role
      routes:
        /github/webhook:
          post:
            function: ${myFunction:name}
#  myEndpoint:
#    type: eventgateway
#    inputs:
#      event: http
#      method: POST
#      path: github-webhook-receiver-eahefnawy
#      space: eslam
#      eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y
#      lambdaArn: ${myFunction:arn}
  myGithubWebhook:
    type: github
    inputs:
      token: ${GITHUB_TOKEN}
      owner: serverless
      repo: components-eslam
      url: ${myEndpoint:url}
      event: pull_request
