# TODO: move this to the "examples" directory
type: github-webhook-receiver

inputs:
  url: http://example.com/webhook

components:
#  myTable:
#    type: dynamodb
#    inputs:
#      name: github-webhook-receiver
  myFunction:
    type: lambda
    inputs:
      name: github-webhook-receiver-function
      memory: 512
      timeout: 10
      handler: code.handler
  myEndpoint:
    type: apigateway
    inputs:
      name: github-webhook-receiver-api
      routes:
        /github/webhook:
          post:
            lambdaArn: ${myFunction.arn}
#  myEndpoint:
#    type: eventgateway
#    inputs:
#      event: http
#      method: POST
#      path: github-webhook-receiver-eahefnawy
#      space: eslam
#      eventGatewayApiKey: s0m33v3ntg4t3w4y4p1k3y
#      lambdaArn: ${myFunction:arn}
  myGithubWebhook:
    type: github
    inputs:
      token: ${GITHUB_TOKEN}
      owner: serverless
      repo: serverless-components
      url: ${myEndpoint.url}
      event: pull_request
