---
type: aws-vpcgatewayattachment
version: 0.2.0
core: 0.2.x

description: "Provision AWS VPC Gateway Attachment with Serverless Components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  internetGatewayId:
    type: string
    description: Intenet Gateway Id
    example: igw-abbaabba
    required: true
  vpcId:
    type: string
    displayName: The id of the VPC
    description: The id of the VPC
    example: vpc-abbaabba
    required: true

outputTypes:
  internetGatewayId:
    type: string
    description: Intenet Gateway Id
