type: s3-prototype

components:
  filesBucket:
    type: s3
    inputs:
      name: serverless-components-eslam-files
  filesTable:
    type: dynamodb
    inputs:
      name: serverless-components-eslam-files
  downloader:
    type: s3-downloader
    inputs:
      name: eslam-hefnawy-downloader
  uploader:
    type: s3-uploader
    inputs:
      name: eslam-hefnawy-uploader
