type: dynamodb-model

inputs:
  region: us-east-1
  tables:
    - name: BlogPost
      hashKey: authorEmail
      rangeKey: title
      provisionedThroughput:
        readCapacity: 2
        writeCapacity: 2
      indexes:
        - name: BlogTitleIndex
          type: global
          hashKey: title
          rangeKey: createdAt
      schema:
        id: uuid
        authorName: string
        authorEmail:
          type: email
          options:
            required: true
        title: string
        content: binary
        tags: stringset
        published:
          type: boolean
          options:
            default: false
      options:
        timestamps: true
    - name: User
      hashKey: email
      indexes:
        - name: UserCityIndex
          type: global
          hashKey: city
      schema:
        fname: string
        lname: string
        email:
          type: email
          options:
            required: true
        city: string
      options:
        timestamps: true
