type: apigateway

inputs:
  name: some-rest-api
  roleArn: ${myRole.outputs.arn}
  routes:
    /hello:
      post:
        lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:some-lambda-function
        cors: true
      get:
        lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:some-lambda-function
    /hello/world:
      delete:
        lambdaArn: arn:aws:lambda:us-east-1:XXXXX:function:some-lambda-function

components:
  myRole:
    type: iam
    inputs:
      name: ${apigateway.inputs.name}
      service: apigateway.amazonaws.com
