type: apigateway

inputs:
  name: some-rest-api
  roleArn: ${myRole:arn}
  routes:
    /hello:
      post:
        function: hello
        cors: true
      get:
        function: hello
    /hello/world:
      delete:
        function: world

components:
  myRole:
    type: iam
    inputs:
      name: ${parent:name}
      service: apigateway.amazonaws.com
