name: AwsProvider
extends: Provider
version: 0.3.0
main: ./dist/index.js

credentials: ${inputs.credentials}
region: ${inputs.region || 'us-east-1'}

inputTypes:
  credentials:
    type: object
    require: false
  region:
    type: string
    require: false
    default: us-east-1
