type: aws-step-functions
version: 0.2.0
core: 0.2.x

description: "A Serverless Component for AWS Step Function"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    required: true
    default: step-functions-${self.instanceId}
    description: The name of the state machine
  definition:
    type: object
    required: true
    description: The Amazon States Language definition of the state machine.
  roleArn:
    type: string
    required: true
    description: The Amazon Resource Name (ARN) of the IAM role to use for this state machine.

outputTypes:
  stateMachineArn:
    type: string
    description: The Amazon Resource Name (ARN) that identifies the created state machine.
  creationDate:
     type: string
     description: The date the state machine is created.



