name: my-api

myLambda:
  component: "@serverless/aws-lambda"
  inputs:
    name: ${name}-lambda
    code: ./code
    handler: index.handler

myApiGateway:
  component: "@serverless/aws-api-gateway"
  inputs:
    name: ${name}-gateway
    routes:
      /foo:
        get:
          function: ${comp:myLambda.arn}
          cors: true
