type: my-project

components:
  myFunction:
    type: lambda
    inputs:
      name: some-function
      memory: 512
      timeout: 10
      handler: handler.handler
      role: ${myRole.arn}
  myRole:
    type: iam
    inputs:
      name: some-role
      service: lambda.amazonaws.com

