type: github-webhook

inputTypes:
  token:
    type: string
    required: true
  owner:
    type: string
    required: true
  repo:
    type: string
    required: true
  url:
    type: string
    required: true
  events:
    type: array
    required: true

inputs:
  token: 14ce2223bcb062f9dd63977f2b1c43ccde917723
  owner: DavidTron5000
  repo: responsible
  url: http://yyyy.com
  events:
    - create
